### PR TITLE
Add issue forms

### PR DESCRIPTION
**Pull request by vuki656**
Hey, really cool work you're doing here :heart: 

I added issue templates to help you handle `feature requests` and `bugs`, and also redirect people to `discussions` if they only have questions. 

For `bug` reports I followed the [CONTRIBUTING.md](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md) in order to setup the questions.

You can see a live preview at [my fork](https://github.com/vuki656/neorg/issues)

Let me know what you think.

### CODE REVIEW

**Comment by vhyrro** [comment]
Ohoho this looks fantastic man, thank you so much. I see you've been making some extra commits and changes, are we alright to merge?

**Comment by vuki656** [comment]
Yup, all done. Freel free to merge.

**Comment by vhyrro** [comment]
You mean the log output from neorg.log? Yeah that can stay, it's very useful for debugging

**Comment by vhyrro** [comment]
Actually, hm. Depends on the scenario. Keep it required for now, if need be I'll change it later down the line if there's a lot of issues that don't need it :)

**Comment by vuki656** [comment]
Made it required, good to go now.

**Comment by vhyrro** [comment]
Thx again 💜

**Pull request merged**
